### ISSUE TITLE
Deconstruction is wrong!

### ISSUE THREAD

**Issue by ahmadawais** [MrSaqibAmeen/ES6-Guide#2]
@MrSaqibAmeen this is wrong!

![](http://on.ahmda.ws/oUdE/c)

```js
let person = {name: 'John', age: 25};
let { name } = person;
console.log(name); // John
```

Is the write answer.

**Comment by saqibameen** [comment]
Thanks for pointing out. Fixed now.
![image 2017-12-31 at 4 28 31 am](https://user-images.githubusercontent.com/31374163/34457953-321e96e0-ede3-11e7-9823-e7e26e1bb0cd.png)
