### ISSUE TITLE
Bad Indentation!

### ISSUE THREAD

**Issue by ahmadawais** [MrSaqibAmeen/ES6-Guide#3]
@MrSaqibAmeen 

![image](http://on.ahmda.ws/oTm6/c)

**Comment by saqibameen** [comment]
Fixed.
![image 2017-12-31 at 4 16 29 am 2r3a2i2i0m2d](https://user-images.githubusercontent.com/31374163/34457911-ac125dee-ede1-11e7-9970-c5510cf3fa32.png)

**Comment by ahmadawais** [comment]
@saqibameen close the tickets of whatever gets fixed by adding FIX #3 or the issue number at thr end or your commit messages.
